### PR TITLE
[WIP] Scala meta out

### PR DESCRIPTION
**Pull request by marcin-rzeznicki**
Hey,
I am making this PR to show the progress of migration from scala-meta annotations. I was able to replace  `@autoFunctor` and `@autoFlatMap`. Replacement of remaining annotations will be very similar I assume, so I think this is good moment to comment on the code - if you see anything weird, questionable, please do not hesitate to comment. 
Tests are passing!
PS. After all of the annotations are migrated, I will have to modify the build to get rid of scala-meta and pull in macro-paradise explicitly
PPS. There is no need to merge this PR - once I am done, I will prepare the final PR with all the changes

UPDATE: I've added `@autoInvariant` and `@autoContravariant` as well - they're all roughly the same

### CODE REVIEW

**Comment by kailuowang** [comment]
Thanks!!! I can't say I am scala-reflect macro expert, but this looks sane to me. @joroKr21 WDYT?

**Comment by joroKr21** [comment]
Looks good so far :+1: 

Great stuff @marcin-rzeznicki ! We can review details later, but I like the approach.

I have some a question in general - how much of the old macros do we want to port? Companion object methods and fully refined instances? `apply` method? These are also things we can leave for future work.

**Comment by marcin-rzeznicki** [comment]
Thanks! I am migrating "higher-kinded" annotations then

**Comment by kailuowang** [comment]
@joroKr21 to answer
> how much of the old macros do we want to port? Companion object methods and fully refined instances? apply method? These are also things we can leave for future work.

I tried to spec out requirements in #37. I agree they can be done in multiple stages / PRs.

**Comment by marcin-rzeznicki** [comment]
Actually, after looking more deeply at the code, I think that #37 can be done in one sweep easily. Handling of type members is not that complicated and it's already done for scala meta, there are existing tests etc.

**Comment by marcin-rzeznicki** [comment]
Closing this pull request

**Pull request closed without merging**
