### PR TITLE
Add TraverseK

### PR DESCRIPTION
**Pull request by kubukoz**
For now, just a general idea & a single law and IdK instance. Ideally, all the laws from Traverse could be borrowed and made into the higher-kinded thing.

Let me know what you think!

### CODE REVIEW

**Comment by joroKr21** [comment]
Maybe I'm missing something but actually I don't see a way to implement this for interfaces.

**Comment by kubukoz** [comment]
I suppose we'd need to call all methods indeed (so it becomes impossible if any of a trait's methods have any parameters)... but it's quite useful for case classes parameterized with a type constructor:

```scala
final case class User[F[_]](id: F[Long], name: F[String])
```

Given an instance, which is relatively straightforward:

```scala
implicit val traverseK: TraverseK[User] = new TraverseK[User] {
  override def traverseK[F[_], G[_]: Apply, H[_]](alg: User[F])(fk: F ~> λ[a => G[H[a]]]): G[User[H]] =
    (fk(alg.id), fk(alg.name)).mapN(User[H])
}
```

we can do things like going from `User[F]` to `F[User[Id]]` (or, more generally, from `User[F compose G]` to `F[User[G]]` - that's `sequenceK`).

So regardless of the fact that we can't do this for interfaces (sadly - I didn't think it through before), I think the algebra itself belongs in a library like cats-tagless and could at least have the derivations for data types.

cc @Fristi

**Comment by kubukoz** [comment]
I also have an OptionT instance now...

```scala
implicit def optionTTraverseK[A]: TraverseK[OptionT[*[_], A]] = new TraverseK[OptionT[*[_], A]] {
      def traverseK[F[_], G[_]: Apply, H[_]](alg: OptionT[F, A])(fk: F ~> λ[a => G[H[a]]]): G[OptionT[H, A]] = fk(alg.value).map(OptionT(_))
    }
```

**Comment by joroKr21** [comment]
We have an open issue for case class support: #29

> I also have an OptionT instance now...
Does that mean we can have an instance for `EitherT` as well? How about `EitherK`, `Tuple2K`?

**Comment by joroKr21** [comment]
This would make sense to revive for Scala 3. But I'm not sure what's the correct signature 🤔

**Comment by kubukoz** [comment]
The one I had in my experiments:

```scala
trait TraverseK[Alg[_[_]]] extends FunctorK[Alg] {

  def traverseK[F[_], G[_]: Apply, H[_]](alg: Alg[F])(fk: F ~> λ[a => G[H[a]]]): G[Alg[H]]

  def sequenceK[F[_]: Apply, G[_]](alg: Alg[λ[a => F[G[a]]]]): F[Alg[G]] =
    traverseK[λ[a => F[G[a]]], F, G](alg)(FunctionK.id[λ[a => F[G[a]]]])

  override def mapK[F[_], G[_]](af: Alg[F])(fk: F ~> G): Alg[G] = traverseK[F, cats.Id, G](af)(fk)

  /** Like [[sequenceK]], but with the second effect hardcoded to [[cats.Id]] for better inference.
    */
  def sequenceKId[F[_]: Apply](alg: Alg[F]): F[Alg[cats.Id]] = sequenceK[F, cats.Id](alg)
}
```

**Comment by joroKr21** [comment]
I find it strange that it has 3 type parameters and that we don't use `ApplyK`.
This also looks pretty strange: `F ~> λ[a => G[H[a]]]`

**Comment by joroKr21** [comment]
Although it does look like `Traversable` from `rank2classes` in Haskell:
https://hackage.haskell.org/package/rank2classes-1.5.3.1/docs/Rank2.html#t:Traversable

**Comment by joroKr21** [comment]
@kubukoz idk about you but I sometimes find myself needing something like this:
```scala
trait FunctorK[T[_[_]]] {
  def mapK[F[_]: Functor, G[_]](t: T[F])(f: F ~> G): T[G]
}
```

So that I can map over stuff like `Expr[F[_]](left: F[Expr[F]], op: InfixOp, right: F[Expr[F]])`.
I wonder how a `TraverseK` would look in this case - I guess:

```scala
trait TraverseK[Alg[_[_]]] extends FunctorK[Alg] {
  def traverseK[F[_]: Traverse, G[_]: Apply, H[_]](alg: Alg[F])(fk: F ~> λ[a => G[H[a]]]): G[Alg[H]]
}
```

**Pull request closed without merging**
