### PR TITLE
Migrating microsite to Mdoc

### LINKED ISSUE #62: Migrate to mdoc

### PR DESCRIPTION
**Pull request by gvolpe**
closes #62

### CODE REVIEW

**Comment by gvolpe** [comment]
Running into some issues I'm not sure how to fix, probably related to the way Mdoc works...

```
sbt:rootPrj> mdoc
[warn] Compile / run / javaOptions will be ignored, Compile / run / fork is set to false
[info] running mdoc.Main 
info: Compiling 3 files to /workspace/oss/cats-tagless/docs/target/scala-2.12/resource_managed/main/jekyll
error: /workspace/oss/cats-tagless/docs/docs/faq.md:61:1: could not find implicit value for parameter inst: App.this.Bar[Option]
Bar[Option].a(3)
^^^^^^^^^^^
error: /workspace/oss/cats-tagless/docs/docs/index.md:147:1: could not find implicit value for evidence parameter of type App.this.Increment[[β$4$]cats.free.Free[scala.util.Try,β$4$]]
program[Free[Try, *]](0).foldMap(FunctionK.id)
^^^^^^^^^^^^^^^^^^^^^^^^
error: /workspace/oss/cats-tagless/docs/docs/index.md:183:1: could not find implicit value for parameter exp: App.this.ExpressionAlg[Option]
new StringCalculatorOptionnMain 3s
^^^^^^^^^^^^^^^^^^^^^^^^^^
error: /workspace/oss/cats-tagless/docs/docs/index.md:191:12: could not find implicit value for parameter inst: App.this.ExpressionAlg[Option]
val prod = ExpressionAlg[Option].productK(ExpressionAlg[Try])
           ^^^^^^^^^^^^^^^^^^^^^
error: /workspace/oss/cats-tagless/docs/docs/index.md:200:23: could not find implicit value for parameter inst: App.this.ExpressionAlg[Option]
val listInterpreter = ExpressionAlg[Option].mapK(λ[Option ~> List](_.toList))
                      ^^^^^^^^^^^^^^^^^^^^^
error: /workspace/oss/cats-tagless/docs/docs/index.md:205:70: could not find implicit value for parameter inst: App.this.ExpressionAlg[Option]
val prod4 = ExpressionAlg.product4K(ExpressionAlg[Try], ExpressionAlg[Option], listInterpreter, vectorInterpreter)
                                                                     ^
info: Compiled in 3.73s (6 errors)

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-1f"
[error] Nonzero exit code: 1
[error] (docs / Compile / runMain) Nonzero exit code: 1
[error] Total time: 4 s, completed Dec 29, 2019 8:25:09 PM
```

**Comment by joroKr21** [comment]
I've tried before to figure out the errors and I couldn't 😞

**Review by joroKr21 — APPROVED** [review]
Magically it works now 🤷

**Comment by gvolpe** [comment]
Nice @joroKr21 ! I had forgotten about this PR :smile:

**Comment by joroKr21** [comment]
If you're curious:
> I was too quick to be happy - needed some fixes in #191
> The problem was that importing autoDerive._ from different algebras in the same scope cause a name clash.

**Pull request merged**
