### PR TITLE
[Scala 3] Derive Apply

### PR DESCRIPTION
**Pull request by joroKr21**
Also add a `summonOpt` helper and explicit return types.

### CODE REVIEW

**Comment by pomadchin** [comment]
oh wow 🔥 

What's left of the regular stuff? `FlatMap`, `SemigroupK`, `MonoidK`?

**Comment by joroKr21** [comment]
> What's left of the regular stuff? FlatMap, SemigroupK, MonoidK?

Yep, do you wanna take any?

**Comment by pomadchin** [comment]
I'll grab some from the list once have some time again / if theres still be a need; don't w8 for me tho... summer is incomin 🌞

**Comment by pomadchin** [comment]
But I'll definitely try to sneak in some PRs to help if I can. That's an incredible pace you're holding here 💪 💪 💪

**Comment by joroKr21** [comment]
> I'll grab some from the list once have some time again! / or if theres still be a need; don't w8 for me tho... summer is incomin 🌞

Cool cool, I think `FlatMap` might be the most interesting. Summer here also started, don't have much time 😄

**Pull request merged**
