### PR TITLE
[Scala 3] Add derivation for Contravariant and Invariant

### PR DESCRIPTION
**Pull request by pomadchin**
This PR adds derivation for Contravariant and Invariant ~~, depends on https://github.com/typelevel/cats-tagless/pull/532~~

~~Note: https://github.com/typelevel/cats-tagless/pull/532 should be merged in first, I'll cherry-pick (it's just a single commit) / rebase it on top of main after that.~~

Linked https://github.com/typelevel/cats-tagless/issues/170

### CODE REVIEW

**Comment by joroKr21** [comment]
I merged it https://github.com/typelevel/cats-tagless/pull/532

**Comment by pomadchin** [comment]
@joroKr21 :+1:

**Comment by pomadchin** [comment]
Decided to combine Contravariant and Invariant into a single PR, because they are very simple.

**Review by joroKr21 — APPROVED** [review]
Nice 👍

**Pull request merged**
